spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
JWT.EXPIRATION.ACCESS: 120
JWT.EXPIRATION.REFRESH: 3600
JWT.ENCRYPTION.ENCRYPTION_KEY: encryptionSecret
CLOUD.AWS.S3.CREDENTIALS.ACCESS_KEY: AKIAQWULYLKE4RD276W4
CLOUD.AWS.S3.CREDENTIALS.SECRET_KEY: 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
CORS.ACCEPTED_ORIGINS: http://localhost:4200
